[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace]
# This ensures the package is not part of the parent workspace

[dependencies]
tos-vm-sdk = { path = "../../sdk" }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
