[package]
name = "terminos-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
terminos-types = { path = "../types" }
terminos-ast = { path = "../ast" }
terminos-environment = { path = "../environment" }
thiserror = "2.0.1"
paste = "1.0.15"
anyhow = "1.0.95"
log = "0.4.25"
