[package]
name = "tos-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
tos-types = { path = "../types" }
tos-ast = { path = "../ast" }
tos-environment = { path = "../environment" }
thiserror = "2.0.1"
paste = "1.0.15"
anyhow = "1.0.95"
log = "0.4.25"
